# Scoring options
FREQ = [
    {"label": "Siempre",       "value": "siempre",       "points": 10},
    {"label": "Casi siempre",  "value": "casi_siempre",  "points": 8},
    {"label": "A veces",       "value": "a_veces",       "points": 5},
    {"label": "Casi nunca",    "value": "casi_nunca",    "points": 2},
    {"label": "Nunca",         "value": "nunca",         "points": 0},
]
FREQ_R = [  # reversed (Nunca = best)
    {"label": "Nunca",         "value": "nunca",         "points": 10},
    {"label": "Casi nunca",    "value": "casi_nunca",    "points": 8},
    {"label": "A veces",       "value": "a_veces",       "points": 5},
    {"label": "Casi siempre",  "value": "casi_siempre",  "points": 2},
    {"label": "Siempre",       "value": "siempre",       "points": 0},
]
YES_NO = [
    {"label": "Sí",       "value": "si",       "points": 10},
    {"label": "No sé",    "value": "no_se",    "points": 5},
    {"label": "No",       "value": "no",       "points": 0},
]
SLEEP_H = [
    {"label": "7 a 8 horas",      "value": "7_8h",   "points": 10},
    {"label": "6 a 7 horas",      "value": "6_7h",   "points": 7},
    {"label": "Más de 8 horas",   "value": "mas_8h", "points": 5},
    {"label": "5 a 6 horas",      "value": "5_6h",   "points": 3},
    {"label": "Menos de 5 horas", "value": "menos5h","points": 0},
]
STRESS = [
    {"label": "Muy bajo",    "value": "muy_bajo",   "points": 10},
    {"label": "Bajo",        "value": "bajo",       "points": 8},
    {"label": "Moderado",    "value": "moderado",   "points": 5},
    {"label": "Alto",        "value": "alto",       "points": 2},
    {"label": "Muy alto",    "value": "muy_alto",   "points": 0},
]

QUESTIONS = {
    "tolerancia": [
        {"id": 1,  "text": "¿Soy capaz de escuchar y respetar las opiniones y puntos de vista de los demás, incluso si difieren de los míos?", "options": FREQ},
        {"id": 2,  "text": "¿Puedo mantener la calma y la compostura en situaciones de conflicto o tensión?", "options": FREQ},
        {"id": 3,  "text": "¿Suelo tratar a las personas de manera justa e imparcial, sin prejuicios ni favoritismos?", "options": FREQ},
        {"id": 4,  "text": "¿Estoy dispuesto/a a ceder o comprometerme en situaciones en las que no puedo obtener exactamente lo que quiero?", "options": FREQ},
        {"id": 5,  "text": "¿Muestro comprensión (empatía) hacia las personas que están pasando por dificultades o problemas?", "options": FREQ},
        {"id": 6,  "text": "¿Trato de resolver desacuerdos o conflictos a través del diálogo y la comunicación abierta en lugar de recurrir a la confrontación?", "options": FREQ},
        {"id": 7,  "text": "¿Soy capaz de aceptar críticas constructivas sin reaccionar de manera defensiva?", "options": FREQ},
        {"id": 8,  "text": "¿Mantengo una mente abierta y estoy dispuesto/a a aprender de nuevas experiencias y perspectivas?", "options": FREQ},
        {"id": 9,  "text": "¿Trato a las personas con respeto y cortesía, independientemente de su origen, género, religión u orientación sexual?", "options": FREQ},
        {"id": 10, "text": "¿Estoy dispuesto/a a admitir mis errores y disculparme cuando sea necesario?", "options": FREQ},
    ],
    "habitos": [
        {"id": 11, "text": "¿Consumes alimentos saludables (frutas, verduras, proteínas) de manera regular?", "options": FREQ},
        {"id": 12, "text": "¿Consumes alimentos procesados, comida chatarra o en exceso?", "options": FREQ_R},
        {"id": 13, "text": "¿Realizas actividad física o ejercicio de manera regular?", "options": FREQ},
        {"id": 14, "text": "¿Mantienes una rutina de ejercicio constante durante la semana?", "options": FREQ},
        {"id": 15, "text": "¿Cuántas horas duermes en promedio por noche?", "options": SLEEP_H},
        {"id": 16, "text": "¿Te sientes descansado/a y recuperado/a cuando te levantas?", "options": FREQ},
        {"id": 17, "text": "¿Mantienes un horario de sueño regular (te acuestas y te levantas a la misma hora)?", "options": FREQ},
        {"id": 18, "text": "¿Dedicas tiempo suficiente a actividades productivas y metas personales o profesionales?", "options": FREQ},
        {"id": 19, "text": "¿Planificas tus tareas por escrito o utilizas listas de pendientes para organizarte?", "options": FREQ},
        {"id": 20, "text": "¿Mantienes comunicación regular y significativa con amigos y familiares?", "options": FREQ},
        {"id": 21, "text": "¿Participas en redes o comunidades que te aportan valor y crecimiento personal?", "options": FREQ},
    ],
    "concentracion": [
        {"id": 22, "text": "¿Te distraes con facilidad cuando estás realizando una tarea importante?", "options": FREQ_R},
        {"id": 23, "text": "¿Puedes mantener tu atención en una tarea durante periodos prolongados de tiempo?", "options": FREQ},
        {"id": 24, "text": "¿Con qué frecuencia revisas el teléfono o redes sociales mientras trabajas o juegas?", "options": FREQ_R},
        {"id": 25, "text": "¿Tienes dificultades para mantener el foco cuando enfrentas tareas complejas o desafiantes?", "options": FREQ_R},
        {"id": 26, "text": "¿Las preocupaciones personales o problemas externos interrumpen tu concentración durante el juego?", "options": FREQ_R},
        {"id": 27, "text": "¿El entorno (ruido, personas u otras distracciones) afecta negativamente tu concentración?", "options": FREQ_R},
        {"id": 28, "text": "¿Practicas técnicas de relajación, meditación o mindfulness para mejorar tu concentración?", "options": FREQ},
        {"id": 29, "text": "¿Duermes las horas suficientes para mantener tu concentración y rendimiento al día siguiente?", "options": FREQ},
        {"id": 30, "text": "¿Cómo evalúas tu nivel de estrés general en tu vida cotidiana?", "options": STRESS},
    ],
    "expectativas": [
        {"id": 31, "text": "¿Creo que puedo alcanzar mis metas personales y profesionales si me esfuerzo lo suficiente?", "options": FREQ},
        {"id": 32, "text": "¿Tengo expectativas positivas sobre mi vida en el futuro?", "options": FREQ},
        {"id": 33, "text": "¿Espero que las personas que me rodean actúen con honestidad y justicia hacia mí?", "options": FREQ},
        {"id": 34, "text": "¿Tengo expectativas positivas sobre las relaciones que establezco con los demás?", "options": FREQ},
        {"id": 35, "text": "¿Creo que podré tener éxito en mi carrera o área de desarrollo profesional?", "options": FREQ},
        {"id": 36, "text": "¿Creo que tendré mejores oportunidades de crecimiento personal y profesional en el futuro?", "options": FREQ},
        {"id": 37, "text": "¿Espero mantener una buena salud física y mental a lo largo de mi vida?", "options": FREQ},
        {"id": 38, "text": "¿Tengo una perspectiva positiva sobre mi calidad de vida en general?", "options": FREQ},
    ],
    "disciplina": [
        {"id": 39, "text": "¿Establezco metas claras y específicas para guiar mis acciones diarias?", "options": FREQ},
        {"id": 40, "text": "¿Mantengo el enfoque en mis proyectos o tareas hasta completarlos exitosamente?", "options": FREQ},
        {"id": 41, "text": "¿Planifico mis días con anticipación y sigo un horario o rutina establecida?", "options": FREQ},
        {"id": 42, "text": "¿Evito posponer tareas importantes aunque no tenga ganas de realizarlas en ese momento?", "options": FREQ},
        {"id": 43, "text": "¿Mantengo la motivación y el esfuerzo cuando enfrento obstáculos en el camino a mis metas?", "options": FREQ},
        {"id": 44, "text": "¿Soy consistente en mis tareas y rutinas diarias, incluso cuando es difícil o incómodo?", "options": FREQ},
        {"id": 45, "text": "¿Establezco límites claros para proteger mi tiempo, energía y recursos?", "options": FREQ},
        {"id": 46, "text": "¿Mantengo la calma y el control emocional en situaciones de presión o dificultad?", "options": FREQ},
        {"id": 47, "text": "¿Planifico a largo plazo y tomo decisiones pensando en el impacto sobre mis metas futuras?", "options": FREQ},
        {"id": 48, "text": "¿Mantengo la determinación y el esfuerzo cuando las tareas se vuelven monótonas o poco motivadoras?", "options": FREQ},
    ],
    "paciencia": [
        {"id": 49, "text": "¿Puedo esperar con calma cuando algo no ocurre tan rápido como quisiera, sin sentirme frustrado/a?", "options": FREQ},
        {"id": 50, "text": "¿Mantengo la tranquilidad cuando enfrento demoras o retrasos inesperados?", "options": FREQ},
        {"id": 51, "text": "¿Puedo manejar situaciones de incertidumbre o información ambigua sin impacientarme?", "options": FREQ},
        {"id": 52, "text": "¿Enfrento la incertidumbre sin entrar en pánico ni tomar decisiones apresuradas?", "options": FREQ},
        {"id": 53, "text": "¿Gestiono la frustración de manera constructiva cuando las cosas no salen como espero?", "options": FREQ},
        {"id": 54, "text": "¿Puedo resolver problemas complejos sin perder la compostura ni el control emocional?", "options": FREQ},
        {"id": 55, "text": "¿Recibo las críticas o comentarios negativos sin ponerme a la defensiva?", "options": FREQ},
        {"id": 56, "text": "¿Acepto los comentarios negativos como una oportunidad de aprendizaje y mejora personal?", "options": FREQ},
    ],
    "resiliencia": [
        {"id": 57, "text": "¿Soy capaz de adaptarme a situaciones difíciles o inesperadas con relativa facilidad?", "options": FREQ},
        {"id": 58, "text": "¿Busco soluciones creativas e innovadoras cuando enfrento problemas complejos?", "options": FREQ},
        {"id": 59, "text": "¿Mantengo una actitud positiva y constructiva cuando enfrento adversidades o contratiempos?", "options": FREQ},
        {"id": 60, "text": "¿Me recupero rápidamente de las decepciones, fracasos o situaciones difíciles?", "options": FREQ},
        {"id": 61, "text": "¿Aprendo y me beneficio activamente de las críticas constructivas que recibo?", "options": FREQ},
        {"id": 62, "text": "¿Veo las dificultades y contratiempos como oportunidades de aprendizaje y crecimiento personal?", "options": FREQ},
        {"id": 63, "text": "¿Cuento con relaciones de apoyo sólidas que me ayudan a superar los momentos difíciles?", "options": FREQ},
        {"id": 64, "text": "¿Mantengo la calma en situaciones de alto estrés y evito tomar decisiones impulsivas?", "options": FREQ},
        {"id": 65, "text": "¿Persisto ante las dificultades y no me doy por vencido/a fácilmente frente a los obstáculos?", "options": FREQ},
        {"id": 66, "text": "¿Establezco metas realistas y trabajo de manera consistente y disciplinada para alcanzarlas?", "options": FREQ},
    ],
    "constancia": [
        {"id": 67, "text": "¿Mantengo el compromiso con mis metas a largo plazo, incluso cuando el camino se vuelve difícil?", "options": FREQ},
        {"id": 68, "text": "¿Continúo trabajando en mis proyectos a pesar de los obstáculos o dificultades significativas?", "options": FREQ},
        {"id": 69, "text": "¿Sigo adelante con mis objetivos aunque el proceso se vuelva tedioso, aburrido o rutinario?", "options": FREQ},
        {"id": 70, "text": "¿Mantengo la determinación y el esfuerzo a pesar de los fracasos o retrocesos temporales?", "options": FREQ},
        {"id": 71, "text": "¿Tengo una rutina diaria estructurada que me ayuda a avanzar consistentemente hacia mis metas?", "options": FREQ},
        {"id": 72, "text": "¿Gestiono mi tiempo y recursos de manera disciplinada para lograr mis objetivos?", "options": FREQ},
        {"id": 73, "text": "¿Evito posponer las tareas importantes para mi desarrollo personal o profesional?", "options": FREQ},
        {"id": 74, "text": "¿Mantengo el enfoque y la productividad incluso en días donde la motivación es baja?", "options": FREQ},
        {"id": 75, "text": "¿Distingues claramente entre lo urgente y lo importante para priorizar correctamente tus tareas?", "options": FREQ},
    ],
    "perseverancia": [
        {"id": 76, "text": "¿Mantengo el enfoque en mis tareas y proyectos a largo plazo sin perderme en distracciones?", "options": FREQ},
        {"id": 77, "text": "¿Mantengo la motivación y el entusiasmo cuando enfrento dificultades o retrocesos?", "options": FREQ},
        {"id": 78, "text": "¿Establezco metas claras, específicas y alcanzables que me impulsen a seguir adelante?", "options": FREQ},
        {"id": 79, "text": "¿Asumo la responsabilidad de mis acciones y decisiones, incluso cuando los resultados no son los esperados?", "options": FREQ},
        {"id": 80, "text": "¿Cuando fracaso, lo veo como una oportunidad de aprendizaje y lo intento de nuevo con más información?", "options": FREQ},
        {"id": 81, "text": "¿Busco soluciones creativas y alternativas en lugar de rendirme cuando enfrento obstáculos?", "options": FREQ},
        {"id": 82, "text": "¿Mantengo la calma y la paciencia cuando las cosas no salen como esperaba?", "options": FREQ},
        {"id": 83, "text": "¿Persisto en mis objetivos a pesar de las críticas externas o la falta de apoyo de otros?", "options": FREQ},
        {"id": 84, "text": "¿Mantengo una actitud positiva y esperanzadora incluso cuando enfrento desafíos o adversidades?", "options": FREQ},
        {"id": 85, "text": "¿Continúas trabajando y esforzándote cuando las tareas se vuelven repetitivas o monótonas?", "options": FREQ},
    ],
    "autocontrol": [
        {"id": 86, "text": "Puedo controlar mi enojo y evitar reaccionar impulsivamente cuando me siento frustrado o irritado.", "options": FREQ},
        {"id": 87, "text": "Sé cómo calmarme cuando estoy enojado/a y puedo expresar mis emociones de manera constructiva.", "options": FREQ},
        {"id": 88, "text": "Puedo lidiar con situaciones estresantes sin que mi ansiedad se vuelva abrumadora o paralizante.", "options": FREQ},
        {"id": 89, "text": "Tengo estrategias efectivas para reducir la ansiedad cuando la siento (respiración profunda, meditación, etc.).", "options": FREQ},
        {"id": 90, "text": "Puedo manejar la tristeza, el dolor y la frustración de manera saludable sin que afecten significativamente mi desempeño.", "options": FREQ},
        {"id": 91, "text": "Soy capaz de encontrar formas de recuperarme emocionalmente después de experiencias negativas o dolorosas.", "options": FREQ},
        {"id": 92, "text": "Puedo pensar antes de actuar y evitar decisiones impulsivas que puedan tener consecuencias negativas.", "options": FREQ},
        {"id": 93, "text": "Tengo la capacidad de posponer la gratificación inmediata y tomar decisiones pensando en el largo plazo.", "options": FREQ},
        {"id": 94, "text": "Mantengo el control emocional en situaciones de alta presión, como en manos clave del poker o decisiones críticas.", "options": FREQ},
    ],
    "gestion_tilt": [
        {"id": 95,  "text": "¿Reconozco cuándo estoy en tilt antes de que afecte mis decisiones en la mesa?", "options": FREQ},
        {"id": 96,  "text": "¿Soy capaz de detener una sesión cuando noto que mis emociones están afectando mi juego?", "options": FREQ},
        {"id": 97,  "text": "¿Cuando pierdo una mano importante, puedo mantener la calma y continuar jugando con objetividad?", "options": FREQ},
        {"id": 98,  "text": "¿Tengo un protocolo o rutina establecida para salir del tilt cuando lo detecto?", "options": FREQ},
        {"id": 99,  "text": "¿Analizo después de cada sesión si estuve en tilt en algún momento?", "options": FREQ},
        {"id": 100, "text": "¿Evito aumentar las apuestas o jugar más manos cuando estoy perdiendo como forma de 'recuperar'?", "options": FREQ},
        {"id": 101, "text": "¿Puedo identificar qué tipo de situaciones o jugadores me generan más tilt?", "options": FREQ},
        {"id": 102, "text": "¿Cuando un rival juega mal y gana, puedo aceptarlo como parte de la varianza sin irritarme?", "options": FREQ},
        {"id": 103, "text": "¿Establezco límites de pérdida (stop loss) antes de comenzar una sesión y los respeto?", "options": FREQ},
        {"id": 104, "text": "¿Después de una mala sesión, puedo desconectarme sin seguir pensando en las manos perdidas?", "options": FREQ},
    ],
    "mentalidad_crecimiento": [
        {"id": 105, "text": "¿Veo cada sesión de poker, independientemente del resultado, como una oportunidad de aprendizaje?", "options": FREQ},
        {"id": 106, "text": "¿Dedico tiempo regular al estudio del poker fuera de las sesiones de juego?", "options": FREQ},
        {"id": 107, "text": "¿Busco activamente feedback de otros jugadores o coaches para mejorar mi juego?", "options": FREQ},
        {"id": 108, "text": "¿Cuando cometo un error, lo analizo con objetividad en lugar de castigarme emocionalmente?", "options": FREQ},
        {"id": 109, "text": "¿Considero que mis habilidades de poker pueden mejorar significativamente con esfuerzo y dedicación?", "options": FREQ},
        {"id": 110, "text": "¿Estoy dispuesto/a a bajar de límites si necesito reforzar fundamentos básicos de mi juego?", "options": FREQ},
        {"id": 111, "text": "¿Llevas un registro de manos o sesiones para revisar y aprender de tus errores?", "options": FREQ},
        {"id": 112, "text": "¿Cuando observas a jugadores mejores que tú, te sirve de inspiración en lugar de desanimarte?", "options": FREQ},
        {"id": 113, "text": "¿Adaptas tu estrategia de juego cuando te das cuenta de que algo no está funcionando?", "options": FREQ},
        {"id": 114, "text": "¿Inviertes en tu educación como jugador (libros, cursos, solvers, coaching)?", "options": FREQ},
    ],
}

CATEGORY_INFO = {
    "tolerancia": {
        "label": "Tolerancia",
        "icon": "🤝",
        "color": "#4CAF50",
        "description": "Capacidad de aceptar y respetar las diferencias de los demás, manejar situaciones desafiantes con calma y comprensión.",
        "improvement_tips": [
            "Practica la escucha activa: enfócate completamente en lo que dice la otra persona antes de responder.",
            "Antes de reaccionar, respira profundo y pregúntate: '¿Esto realmente importa a largo plazo?'",
            "Lleva un diario de situaciones donde perdiste la paciencia y analiza qué desencadenó esa reacción.",
            "Exponte conscientemente a perspectivas diferentes a las tuyas para ampliar tu visión.",
            "Practica el rol de 'abogado del diablo': defiende una posición contraria a la tuya para entenderla mejor.",
        ]
    },
    "habitos": {
        "label": "Hábitos",
        "icon": "💪",
        "color": "#2196F3",
        "description": "Rutinas y comportamientos relacionados con la salud física, el descanso y la organización personal que sostienen tu rendimiento.",
        "improvement_tips": [
            "Implementa la regla de los 2 minutos: si una tarea tarda menos de 2 minutos, hazla ahora.",
            "Establece una rutina de sueño fija: acuéstate y levántate a la misma hora todos los días.",
            "Planifica tus comidas semanalmente para evitar decisiones impulsivas poco saludables.",
            "Usa la técnica Pomodoro: 25 minutos de trabajo concentrado, 5 de descanso.",
            "Establece una 'hora digital off' al menos 1 hora antes de dormir.",
        ]
    },
    "concentracion": {
        "label": "Concentración",
        "icon": "🎯",
        "color": "#FF9800",
        "description": "Capacidad de mantener el foco y la atención plena durante el juego y en situaciones de alta demanda cognitiva.",
        "improvement_tips": [
            "Practica meditación de atención plena (mindfulness) al menos 10 minutos al día.",
            "Crea un ambiente de juego libre de distracciones: teléfono en silencio, notificaciones desactivadas.",
            "Utiliza técnicas de visualización antes de cada sesión de poker para entrar en estado de flujo.",
            "Haz ejercicio aeróbico regularmente: mejora el flujo de sangre al cerebro y la concentración.",
            "Practica juegos de memoria o puzzles para entrenar tu capacidad atencional.",
        ]
    },
    "expectativas": {
        "label": "Expectativas",
        "icon": "🌟",
        "color": "#9C27B0",
        "description": "Creencias sobre el futuro y la capacidad para mantener una perspectiva optimista y realista sobre el desarrollo personal.",
        "improvement_tips": [
            "Escribe diariamente 3 cosas positivas que ocurrieron: entrena tu cerebro hacia el optimismo.",
            "Define metas SMART (específicas, medibles, alcanzables, relevantes, con tiempo definido).",
            "Celebra los pequeños logros: cada paso cuenta en el camino hacia la excelencia.",
            "Rodéate de personas con mentalidad de crecimiento que te impulsen hacia arriba.",
            "Lee biografías de jugadores exitosos para inspirarte y calibrar tus expectativas.",
        ]
    },
    "disciplina": {
        "label": "Disciplina",
        "icon": "⚡",
        "color": "#F44336",
        "description": "Capacidad de mantener rutinas consistentes, resistir la procrastinación y actuar en alineación con los objetivos a largo plazo.",
        "improvement_tips": [
            "Usa el método 'Eat the frog': comienza el día con la tarea más difícil o importante.",
            "Diseña tu entorno para el éxito: elimina las tentaciones que te desvían de tus metas.",
            "Crea un sistema de recompensas para celebrar el cumplimiento de tu rutina.",
            "Practica decir NO a las actividades que no se alinean con tus objetivos de poker.",
            "Lleva un registro diario de tus horas de estudio y práctica para mantener la accountability.",
        ]
    },
    "paciencia": {
        "label": "Paciencia",
        "icon": "⏳",
        "color": "#00BCD4",
        "description": "Habilidad para esperar serenamente resultados, tolerar la incertidumbre y mantener la compostura bajo presión.",
        "improvement_tips": [
            "Practica la meditación de la 'tormenta de pensamientos': observa sin reaccionar.",
            "Cuando sientas impaciencia, cuenta hasta 10 lentamente y respira antes de actuar.",
            "Estudia la teoría de la varianza en poker: comprende que los resultados a corto plazo son impredecibles.",
            "Lleva un 'diario de emociones' durante tus sesiones para identificar patrones de impaciencia.",
            "Practica juegos que requieran esperar el momento justo para actuar (ajedrez, etc.).",
        ]
    },
    "resiliencia": {
        "label": "Resiliencia",
        "icon": "🔄",
        "color": "#607D8B",
        "description": "Capacidad de adaptarse y recuperarse rápidamente ante situaciones adversas, manteniendo una perspectiva de crecimiento.",
        "improvement_tips": [
            "Después de cada sesión, analiza los errores sin juicio: ¿qué aprendiste?",
            "Desarrolla un ritual de 'reset': una actividad que te ayude a salir del tilt rápidamente.",
            "Construye una red de apoyo de jugadores de mentalidad similar para compartir experiencias.",
            "Practica el reencuadre cognitivo: ¿cómo vería esta situación alguien con más experiencia?",
            "Lleva un registro de tus 'malas rachas' anteriores y cómo las superaste para recordar tu fortaleza.",
        ]
    },
    "constancia": {
        "label": "Constancia",
        "icon": "📈",
        "color": "#795548",
        "description": "Persistencia en el esfuerzo a lo largo del tiempo, manteniendo el compromiso con los objetivos más allá de la motivación momentánea.",
        "improvement_tips": [
            "Establece metas de proceso (horas de estudio/semana) no solo de resultado (ganancias).",
            "Usa la técnica del 'Habit Stacking': une un nuevo hábito a uno ya establecido.",
            "Crea un tablero visual de tus metas donde puedas ver tu progreso diariamente.",
            "Comprométete públicamente con tus objetivos: la responsabilidad social aumenta la constancia.",
            "Divide los grandes objetivos en micro-metas semanales para mantener el momentum.",
        ]
    },
    "perseverancia": {
        "label": "Perseverancia",
        "icon": "🏆",
        "color": "#FF5722",
        "description": "Determinación para continuar a pesar de los fracasos, asumiendo la responsabilidad y aprendiendo de cada experiencia.",
        "improvement_tips": [
            "Reencuadra el fracaso: cada mano perdida es información, no un fracaso personal.",
            "Lee sobre el concepto de 'Grit' de Angela Duckworth: la pasión y la perseverancia superan al talento.",
            "Establece un 'por qué' profundo: ¿cuál es tu motivación más poderosa para ser un gran jugador?",
            "Crea afirmaciones positivas específicas al poker y repítelas cada mañana.",
            "Documenta tu progreso: ver el avance acumulado te dará fuerzas en los momentos difíciles.",
        ]
    },
    "autocontrol": {
        "label": "Autocontrol Emocional",
        "icon": "🧠",
        "color": "#3F51B5",
        "description": "Capacidad de gestionar las emociones intensas, evitar reacciones impulsivas y tomar decisiones racionales bajo presión.",
        "improvement_tips": [
            "Implementa la regla de los 10 segundos antes de cualquier decisión importante en la mesa.",
            "Aprende técnicas de respiración para bajar la activación emocional: inhala 4s, retén 4s, exhala 4s.",
            "Practica el 'stop loss emocional': define un umbral de pérdida tras el cual te retiras de la sesión.",
            "Estudia el concepto de 'tilt' y sus variantes para reconocerlo antes de que afecte tu juego.",
            "Trabaja con un coach mental o psicólogo deportivo especializado en deportes de alta competencia.",
        ]
    },
    "gestion_tilt": {
        "label": "Gestión del Tilt",
        "icon": "🌡️",
        "color": "#E91E63",
        "description": "Capacidad de detectar, controlar y salir del estado de tilt antes de que comprometa tu toma de decisiones y resultados en la mesa.",
        "improvement_tips": [
            "Lleva un 'termómetro de tilt': califica tu estado emocional del 1 al 10 cada 30 minutos de juego.",
            "Crea una señal de alarma personal que actives cuando notes los primeros síntomas de tilt.",
            "Estudia los tipos de tilt: por mala suerte, por errores propios, por jugadores irritantes.",
            "Implementa un descanso obligatorio de 10 minutos cuando pierdas 3 manos importantes seguidas.",
            "Practica la técnica del 'observador externo': analiza tu juego como si fueras otro jugador.",
        ]
    },
    "mentalidad_crecimiento": {
        "label": "Mentalidad de Crecimiento",
        "icon": "🌱",
        "color": "#8BC34A",
        "description": "Disposición a aprender continuamente, aceptar el error como parte del proceso y comprometerse con la mejora constante como jugador.",
        "improvement_tips": [
            "Reserva al menos 30 minutos diarios para estudiar poker: solvers, vídeos, libros o revisión de manos.",
            "Adopta el lema 'cada error es un maestro': anota las manos donde dudaste y estúdialas al día siguiente.",
            "Busca un grupo de estudio con jugadores de tu nivel para crecer juntos.",
            "Usa software de análisis (GTO Wizard, Pio Solver) para detectar brechas entre tu juego y el óptimo.",
            "Establece metas de aprendizaje mensuales específicas: dominar un concepto de rangos, mejorar el c-bet, etc.",
        ]
    },
}
